name: CI/CD pipeline

on:
    push:
        branches: main

jobs:
    build-push-job:
        runs-on: ubuntu-latest

        steps:
            - name: code checkout
              uses: actions/checkout@v3

            - name: docker-build
              uses: docker/setup-buildx-action@v2

            - name: login to dockerhub
              uses: docker/login-action@v2
              with:
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_PASSWORD}}

            - name: build-push-docker-image
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: ${{secrets.DOCKER_USERNAME}}/new_api:latest

    deploy-aws:
        runs-on: ubuntu-latest

        steps:
            - name: Download ssh key
              run: |
                echo "${{secrets.EC2_KEY}}" > key.pem
                chmod 400 key.pem

            - name: Deploy to EC2
              run: |
                ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
                    docker stop fastapi-container || true
                    docker rm fastapi-container || true
                    docker pull ${{ secrets.DOCKER_USERNAME }}/new_api:latest
                    docker run -d --name new_api-container -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/new_api:latest
                EOF